### PR TITLE
Epics/398/backend/431-1

### PR DESCRIPTION
**Pull request by carltonsmith**
### This pull request changes...

Add blank reports app

## FUNCTIONALITY

Plumbing for [431](https://github.com/raft-tech/TANF-app/issues/431), before this ticket we did not have a concept of a report in the backend service.

## TO TEST

This PR doesn't add or change anything testable at this time. It's a thin slice PR that contributes to meeting the AC in [431](https://github.com/raft-tech/TANF-app/issues/431)

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Comment by hursey013** [comment]
@carltonsmith @riatzukiza Digging the smaller PRs! I am curious with this particular one if anything is generated when creating the reports app? Is there a URL I confirm is present, or is this purely a backend change?

I think in the future it would be great to organize these PRs into smaller chunks as you are, but in a way that we have something testable with each one, even if it's minimal (confirming that the endpoint exists for example, and finer grained tests in future PRs).

**Comment by carltonsmith** [comment]
> @carltonsmith @riatzukiza Digging the smaller PRs! I am curious with this particular one if anything is generated when creating the reports app? Is there a URL I confirm is present, or is this purely a backend change?
> 
> I think in the future it would be great to organize these PRs into smaller chunks as you are, but in a way that we have something testable with each one, even if it's minimal (confirming that the endpoint exists for example, and finer grained tests in future PRs).

Thanks for taking a look @hursey013 - That was actually the issue we ran into with this. The large PR was necessary to have something to test. We really need to choose what way we want to go when confronted with this choice. Are we biased towards smaller PRs or testable changes? I can definitely understand why both would be wanted, but there are times, such as this, where we have to go one way or the other.

**Comment by hursey013** [comment]
@carltonsmith Yeah, totally see what you are saying. I think smaller PRs will ultimately provide the most benefit in terms of code review and getting code merged in. 431 might not be the best example, so my comment is less about this group of PRs specifically, more just an observation on future PRs and working towards the smallest PR possible while still introducing a testable change.

**Comment by hursey013** [comment]
### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

**403:**
+ [ ] Create Django App reports
+ [ ] Add fields to store file data to reports model (should include slug, fk to user, fk to stt
+ [ ] Add model class for reports logging (need to log updates to the file - date/time, operation (create or update) and fk to user and fk to report) (we can add file diff here later if/when that becomes a requirement)
+ [ ] Create POST endpoint to accept file data
+ [ ] Update reports/views.py
+ [ ] Update reports/serializers.py
+ [ ] Create migrations for reports and logging
+ [ ] Add tests as needed

As Product Owner, @lfrohlich will decide if ACs are met.

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: 99% (see https://github.com/raft-tech/TANF-app README coverage dashboard)
  + [ ] Backend coverage: 100% (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*

_N/A, no frontend changes._

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

+ [ ] If this PR introduces backend code, is that code documented both inline and overall?

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

+ [ ] Does the OWASP Scan pass on CircleCI?

**Comment by carltonsmith** [comment]
Thanks for the review @hursey013! I see that there is no approval but I don't see any changes requested. Is there something else we need to do on this?

**Comment by hursey013** [comment]
@lfrohlich, based on the QASP review above I recommend that you merge this PR and accept this work.

**Review by hursey013 — APPROVED** [review]

**Review by lfrohlich — APPROVED** [review]
Looks good, thanks

**Comment by alexsoble** [comment]
(Closing and opening the PR to kick the tires on CircleCI and see if it gets the tests to run.)

**Pull request merged**
