### PR TITLE
406 header focus fix

### PR DESCRIPTION
**Pull request by carltonsmith**
### This pull request changes...

Now when a user is routed to a new page, a screen reader will automatically read out the new `h1`. Also, if there is an alert that comes up (e.g. Network Error, Please Sign In) then a screen reader will now announce that alert.

## FUNCTIONALITY
*Describe the functionality*
Addresses issues: #406 and #407 

## TO TEST
406
1. Go to `/edit-profile` and fill out the form.
2. Fill out form
3. Turn on screen reader
4. Click on `Request Access` and it should then announce the `h1` of the new page which is `Request Submitted`

407
1. Go to `/edit-profile` and fill out the form.
2. Open DevTools and set `Network` to `Offline`
3. Click on `Request Access`
4. It should read out `Network Error` while maintaining focus on the `Request Access` button. (I discussed whether this should be focused or simply read with Robert and we settled on just being read for now but happy to reassess).

### This pull request is ready to merge when...

- [x] Meets acceptance criteria for the issue 
- [x] Code is reviewed by someone other than the original author
- [x] Code is tested 
- [x] Experience is approved by UX  
- [x] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [x] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [x] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Comment by alexsoble** [comment]
Pinging @ttran-hub / @iamjolly for a11y review. 👋 😄 👋 😄

**Comment by iamjolly** [comment]
@alexsoble, @carltonsmith, @hilvitzs, and @ttran-hub ... I was able to test this a bit today and I think it's not setting focus to the `h1` as intended in #158. I am finding that after I submit the request access form the focus is set to the `body` element. 

I can post a short screencast of this if you want/need.

**Comment by hilvitzs** [comment]
@iamjolly Hey thanks so much for taking a look! Sorry but the changes for this PR weren't live on the cloud environment since we had to do some other testing. They are up now and everything should be working as expected! Someday soon we'll hopefully have another environment so this doesn't keep happening. 

It might be helpful if you let us know when you're going to take a look so that we can ensure that the right code has been pushed and is ready. I don't like taking up your time on multiple occasions because we have to test other code. I'm also open to other solutions if anyone has them, I just don't know of any way to make this better until we get another environment.

**Comment by iamjolly** [comment]
> It might be helpful if you let us know when you're going to take a look so that we can ensure that the right code has been pushed and is ready.

I'll definitely do that until y'all say there's another environment to test things in. 

So... this looks a-okay to me for both 406 and 407. Those behave as described and expected! 

It does appear that there is some other polling happening around logged-in state that redirects fairly quickly back to the Sign In page (or a cached version of it) when I set the Network to offline in devtools. I don't think that's a terrible thing, though. Have you all seen this too?

**Comment by hilvitzs** [comment]
@iamjolly Thanks for taking a look!

Yes, I noticed that and was confused at first too but it is actually expected behavior. Events are throttled by the idleTimer so that every minute (upon user action) an auth_check request is sent to make sure that they stay logged in. When you're offline that can't be successful so it automatically kicks the user out of the application.

**Review by iamjolly — APPROVED** [review]

**Comment by hursey013** [comment]
@hilvitzs just ran through this locally and confirmed it works as expected 🎉  This feels like a pretty critical piece of a11y functionality - would it be possible to add a unit test to confirm the `<h1 />` is in focus?

**Comment by hilvitzs** [comment]
@hursey013 Yes! I think I had one so it must be on a separate branch. Let me find it and make sure it's included in this PR. Thanks for finding that.

**Comment by hilvitzs** [comment]
@hursey013 Alright those should be up there now. Sorry about that! The coverage is saying that one of the lines isn't covered but it is. Let me know if it's missing anything else.

**Comment by hursey013** [comment]
### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

As Product Owner, @lfrohlich will decide if ACs are met.

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: ___ (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Does this PR change any linting or CI settings?

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*

+ [ ] Did automated and manual testing with @iamjolly and @ttran-hub using Accessibility Insights reveal any errors introduced in this PR?
    + [See the full Accessibility Assessment plan here.](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

+ [ ] If this PR introduces frontend code, is that code documented both inline and overall?

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any security issues?

**Comment by hursey013** [comment]
@lfrohlich, based on the QASP review above I recommend that you merge this PR and accept this work.

**Review by hursey013 — APPROVED** [review]
🚀

**Pull request merged**
