### PR TITLE
Remove archived prototype code

### PR DESCRIPTION
**Pull request by alexsoble**
## ZenHub Issue 

https://github.com/raft-tech/TANF-app/issues/263

## Archives of prototype codebase

* Prototype code as of Mar 26, 2020 archived here: https://github.com/HHS/TANF-app-archive
* Prototype code as of Feb 25, 2020 archived here: https://github.com/18F/tanf-prototype

## Files and folders kept vs archived 

Checklist of files and folders in the root directory of https://github.com/HHS/TANF-app-archive: 

+ .circleci — Kept
+ compliance — Archived
+ docs — Kept
+ tanf — Archived
+ upload — Archived
+ users — Archived 
+ utilities — Archived
+ .cfignore — Kept
+ .dockerignore — Kept
+ .gitignore — Kept
+ Dockerfile — Archived
+ LICENSE — Kept
+ Procfile — Kept
+ README.md  — Archived
+ delete-cloudgov.sh — Archived
+ deploy-cloudgov.sh — Archived
+ docker-compose.yml — Archived
+ generate-compliance-pdf.sh — Archived
+ manage.py — Archived
+ requirements.txt — Kept
+ runtime.txt — Kept
+ test.sh — Archived

## Branch preview link 

https://github.com/HHS/TANF-app/tree/ars/remove-archived-prototype-code

### CODE REVIEW

**Comment by alexsoble** [comment]
@carltonsmith Asking for your review here before I advance this PR forward — I could use a second pair of eyes familiar with the app to make sure that none of the archived/removed files play any role outside the prototype. Thank you!

**Comment by alexsoble** [comment]
Note that this PR leaves the main README as a bit of a stub, but we have a prioritized task to update the README in the next sprint: https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/17

**Review by carltonsmith — APPROVED** [review]
This looks good. I don't see anything we are still using here.

**Comment by alexsoble** [comment]
Great, thanks @carltonsmith! Tagging @lfrohlich for the next layer of review — Lauren, let's discuss this one tomorrow either sync or async!

**Review by lfrohlich — APPROVED** [review]
This looks good, thanks

**Comment by alexsoble** [comment]
Great! @carltonsmith, I don't expect you to see any issues the next time you deploy to dev, but let me know if you do!

**Pull request merged**
