### PR TITLE
Remove lingering prototype files

### PR DESCRIPTION
**Pull request by alexsoble**
## Issue 

https://github.com/raft-tech/TANF-app/issues/263

## Notes 

Spotted lingering files from the prototype code that I must have missed the first time around. 

## What this removes / cleans up

+ From the root directory, unused .cfignore, .dockerignore, and .gitattributes (all prototype-related) — see more about why here: https://github.com/HHS/TANF-app/pull/150#issuecomment-763684570
+ From the root directory, unused /static folder (prototype-related) — see more about why here and here: https://github.com/HHS/TANF-app/pull/150#issuecomment-763713520, https://github.com/HHS/TANF-app/pull/150#issuecomment-763945802
+ From the root directory, unused Pipfile, .procfile, Procfile — these are all prototype-related and the up-to-date versions are stored in the backend directory

### CODE REVIEW

**Comment by alexsoble** [comment]
We have so few files left in the root directory now! Almost all folders, plus the README, LICENSE, and a few scripts ...

Of the remaining files in the root directory, I see three more that we might want to remove beyond the 6 I am already removing here: 

### `.cfignore`

I (incorrectly) assumed this file was relevant since the `.gitignore` file in the root is still relevant. Taking a closer look at the contents, none of the files/folders seem relevant or ignore-worthy, e.g. `*.sqlite3`. 

More on `.cfignore` here — https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html — "Especially with a large app, uploading unnecessary files can slow app deployment."

My thinking right now is that we should remove this one. We may want to add `.cfignore` files to both the frontend and the backend folders so as not to deploy things like documentation and scripts to Cloud.gov, but doing so does not seem urgent or security-related. 

### `.dockerignore`

I (incorrectly) assumed this was relevant since the `.gitignore` file in the root is still relevant. Taking a closer look at the contents, none of the files/folders seem relevant or ignore-worthy, e.g. `*.sqlite3`. 

The `.dockerignore` file is more important than `.cfignore` since our Docker images are public, and using `.dockerignore` helps add a layer of protection against accidentally publishing secrets: https://docs.docker.com/engine/reference/builder/#dockerignore-file

I'm noticing the the frontend has its own `.dockerignore` but the backend does not, I think we should add one on the backend. (I can make a ZenHub ticket.)

### `.gitattributes`

Since this references two prototype files that have been removed, this can/should also be removed.

---

@carltonsmith @hursey013 — Whaddaya think? Am I missing any more files in this roundup of lingering prototype files?

**Review by carltonsmith — APPROVED** [review]
@alexsoble I think using separate `.gitignore` and `.dockerignore` files for each separate application makes a lot of sense. At any rate, these changes look good to me

**Comment by alexsoble** [comment]
@carltonsmith Thanks! Thanks also for catching two more:

### `/static` 

Hasn't been updated for ~6 months, looks like frontend work that has since moved to the frontend repo.

### `/scripts`

Hasn't been updated for ~6 months, these look like dev/infrastructure scripts that haven't been used or referenced since Sprint 1. Not prototype code, but I think we can safely remove these if devs aren't using them for anything.

**Review by hursey013 — APPROVED** [review]
Looks good!

**Comment by hilvitzs** [comment]
I can't approve this PR but removing `/static` should not cause any issues.

**Comment by alexsoble** [comment]
@hilvitzs Thanks!

**Review by lfrohlich — APPROVED** [review]
Looks good

**Pull request merged**
