### PR TITLE
Draft: Add Docker ADR

### PR DESCRIPTION
**Pull request by hursey013**
### This pull request changes...

Backfilling decision to use Docker in the production environment.

### CODE REVIEW

**Comment by hursey013** [comment]
@carltonsmith this decision predates me - is there any additional context re:Docker that would be helpful to capture and explain here?

**Comment by alexsoble** [comment]
@hursey013 Couple of things:

1. The deployment flow PR was 008, so this would be ADR 009. 📈 
2. I noticed the date on this decision is in the past -- does that mean these are words that were written back in August of last year, or are they new words you wrote to describe a past choice?
3. If it's the latter -- worth noting that we could use Docker in local environments and CI, but use a Cloud.gov buildpack in production? Which would let us keep Docker portability benefits and getting more Cloud.gov security benefits at the same time?

**Comment by hursey013** [comment]
> @hursey013 Couple of things:
> 
> 1. The deployment flow PR was 008, so this would be ADR 009. 📈
> 2. I noticed the date on this decision is in the past -- does that mean these are words that were written back in August of last year, or are they new words you wrote to describe a past choice?
> 3. If it's the latter -- worth noting that we could use Docker in local environments and CI, but use a Cloud.gov buildpack in production? Which would let us keep Docker portability benefits and getting more Cloud.gov security benefits at the same time?

All great questions @alexsoble! Rather than using this to backfill a past decision, I'm going to pull this one back into `Draft` mode until we have a chance to talk through some of these with the larger team, especially bullet point 3.

**Comment by carltonsmith** [comment]
> @carltonsmith this decision predates me - is there any additional context re:Docker that would be helpful to capture and explain here?

Yes @hursey013 I have submitted [a PR](https://github.com/HHS/TANF-app/pull/173) to this branch to add some additional context

**Comment by lfrohlich** [comment]
Note we may want to keep this documentation for using docker locally.

**Comment by hursey013** [comment]
I'm going to close this for now because I think a more timely and relevant ADR should be created based on the pros/cons of using Docker images or cloud.gov buildpacks in the various deployed environments.

**Pull request closed without merging**
