### PR TITLE
Add "How ACF and 18F will evaluate accessibility" documentation

### PR DESCRIPTION
**Pull request by alexsoble**
## Document preview

https://github.com/HHS/TANF-app/blob/ars/18f-a11y-approach/docs/a11y/how-18f-will-test-a11y.md

## This pull request addresses 

https://github.com/raft-tech/TANF-app/issues/316

## Notes

Create new `a11y` sub-folder under `docs` and move RAFT a11y notes into that same folder.

### CODE REVIEW

**Comment by alexsoble** [comment]
@iamjolly I think you make sense as the reviewer here since you've been leading this area of review/evaluation! Let me know what you think — does this seem like a fair representation of our discussion yesterday, and a good starting point? Very open to comments/suggestions/questions!

**Comment by alexsoble** [comment]
@iamjolly I'll also put this on the agenda for tomorrow's internal 18F meeting in case others on the project team have questions or perspectives

**Review by iamjolly — APPROVED** [review]
Looks like a very clear summation of our discussion and decisions @alexsoble. Thank you!

**Comment by alexsoble** [comment]
@iamjolly Terrific, glad to hear it! I'll keep this PR open and in WIP mode until I've had a chance to share and incorporate feedback from all parts of the team and especially our Product Owner!

**Comment by alexsoble** [comment]
### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

How to check: 

+ [x] Look up the acceptance criteria in the related issue
+ [x] Check against the below criteria: 
+ [x] Work with Robert Jolly and understand his go-to a11y testing set up 
+ [x] Use that information to take a first pass at a written plan for how 18F and OFA will approach a11y testing

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

How to check: 

_This is a documentation-only PR and does not affect code coverage._

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

_This PR does not affect code styling; no Python or Javascript changes made._

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*

_This PR does not affect accessibility; no front-end changes._

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

How to check: 

_This is a documentation-only PR and does not affect the deploy process._

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

How to check: 

+ [x] This PR adds documentation on 18F QASP checks. 

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

How to check: 

_This is a documentation-only PR and does not affect security._

**Comment by alexsoble** [comment]
@lfrohlich Ideally we'd have a passing test suite, but since this PR is documentation-only, it feels safe to merge; we know it's not causing the tests to fail. (We're fixing up our test suite in a separate PR, #69.) 

If you approve, I recommend merging this work to the HHS repo. @iamjolly has already approved.

**Review by lfrohlich — APPROVED** [review]
This looks good to me! Thanks!

**Pull request merged**
