### PR TITLE
Idle timer events fix

### PR DESCRIPTION
**Pull request by carltonsmith**
### This pull request changes...

- Add `REACT_APP_EVENT_THROTTLE_TIME` variable to `.env.development` to throttle events on idleTimer to help with performance.
- Add environment variables from `.env.development` to `.env.test`.
- Fix linting errors in `EditProfile` component
- Add `focus` event to events that count for activity on the `idleTimer` component.
- Update tests accordingly
- Update idleTimer id `myModal` to `timeoutModal` for clarity.
- Closes [#474](https://app.zenhub.com/workspaces/tdrs-sprint-board-5f18ab06dfd91c000f7e682e/issues/raft-tech/tanf-app/474)

## FUNCTIONALITY
Now, `focus` will count as an activity that will prevent the user from being timed out. This is in response to a small accessibility concern from Robert Jolly having to do with someone using a screen reader being timed out.

This will also batch those events and only allow them to be triggered every 60 seconds to prevent performance issues.

## TO TEST

Not entirely sure how to demonstrate this one. We can discuss it.

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Review by iamjolly — CHANGES_REQUESTED** [review]
The timeout that fires after 20 minutes of idle time has a problem. The modal appears and then immediately logs you out, which indicates that there is no timer running to allow folks to adequately respond to the timeout/extend session warning prompt.

Attached is a trimmed video that captured this behavior (MacOS, Chrome). HT to @ttran-hub for spotting the issue during his testing!

Video only (no audio):
https://user-images.githubusercontent.com/1093423/104345274-6381ca80-54bb-11eb-831c-5da853e2c4d9.mov

**Comment by hilvitzs** [comment]
@iamjolly Thank you for finding this issue. Usually, this means that the env variable for `REACT_APP_LOGOUT_TIME` is not being set correctly. @carltonsmith do you mind if I manually deploy and try to make sure that that's set?

**Comment by carltonsmith** [comment]
> @iamjolly Thank you for finding this issue. Usually, this means that the env variable for `REACT_APP_LOGOUT_TIME` is not being set correctly. @carltonsmith do you mind if I manually deploy and try to make sure that that's set?

No, that's not a problem

**Comment by hilvitzs** [comment]
Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?

**Comment by iamjolly** [comment]
> Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?

@hilvitzs - Awesome. I'd love to have it set at about 2 or 3 minutes idle time for testing, if that's no problem for you. Waiting 20 minutes feels like foooorrrevvverrrrr!

**Comment by hilvitzs** [comment]
> > Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?
> 
> @hilvitzs - Awesome. I'd love to have it set at about 2 or 3 minutes idle time for testing, if that's no problem for you. Waiting 20 minutes feels like foooorrrevvverrrrr!

Haha 20 minutes is way too long for testing. No problem at all! It is set to 2 minutes for the modal to come up and then another minute for the logout. I tested it and it looks like it's working but let me know if something else is wrong. Thanks again!

**Comment by ttran-hub** [comment]
> > > Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?
> > 
> > 
> > @hilvitzs - Awesome. I'd love to have it set at about 2 or 3 minutes idle time for testing, if that's no problem for you. Waiting 20 minutes feels like foooorrrevvverrrrr!
> 
> @iamjolly haha 20 minutes is way too long for testing. No problem at all! It is set to 2 minutes for the modal to come up and then another minute for the logout. I tested it and it looks like it's working but let me know if something else is wrong. Thanks again!

**Comment by ttran-hub** [comment]
> > > > Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?
> > > 
> > > 
> > > @hilvitzs - Awesome. I'd love to have it set at about 2 or 3 minutes idle time for testing, if that's no problem for you. Waiting 20 minutes feels like foooorrrevvverrrrr!
> > 
> > 
> > @iamjolly haha 20 minutes is way too long for testing. No problem at all! It is set to 2 minutes for the modal to come up and then another minute for the logout. I tested it and it looks like it's working but let me know if something else is wrong. Thanks again!

@hilvitzs, thanks for making the testing time shorter.  Tested and it's working for 2 min. idles and additional minute

**Comment by ttran-hub** [comment]
> > > > > Alright, it looks like there's a problem with our automatic deploys not getting the correct variables. I manually deployed and that seems to have fixed the problem. @iamjolly or @ttran-hub I can make that timeout any amount of time. Do you want to test the production values or would you prefer the times to be shorter so it's quicker to verify?
> > > > 
> > > > 
> > > > @hilvitzs - Awesome. I'd love to have it set at about 2 or 3 minutes idle time for testing, if that's no problem for you. Waiting 20 minutes feels like foooorrrevvverrrrr!
> > > 
> > > 
> > > @iamjolly haha 20 minutes is way too long for testing. No problem at all! It is set to 2 minutes for the modal to come up and then another minute for the logout. I tested it and it looks like it's working but let me know if something else is wrong. Thanks again!
> 
> @hilvitzs, thanks for making the testing time shorter. @iamjolly, did the initial test and it's working for 2 min. idles and additional minute looks like working as describes

**Comment by iamjolly** [comment]
Fantastic @ttran-hub. I'm seeing the same thing you are with this update. This looks good-to-go from an accessibility perspective.

**Review by iamjolly — APPROVED** [review]

**Comment by hilvitzs** [comment]
Awesome. Thank you both!

**Review by lfrohlich — APPROVED** [review]
ACs look good to me!

**Review by alexsoble — APPROVED** [review]
# QASP Review

### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

+ [x] As Product Owner, @lfrohlich will decide if ACs are met — ACs approved by Lauren.

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

+ Are code coverage minimums met?
  + [x] Frontend coverage: 100% (see https://github.com/raft-tech/TANF-app README coverage dashboard)
  + [x] Backend coverage: 100% (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

+ [x] Backend code style checks passing on CircleCI
+ [x] Frontend code style checks passing on CircleCI

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*

+ [x] Automated and manual testing with @iamjolly and @ttran-hub using Accessibility Insights passed 

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

+ [x] Code successfully deployed via automated CircleCI process to development on Cloud.gov

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

+ [x] If this PR introduces frontend code, is that code documented both inline and overall? — Yes, `.env.test` is well commented and documented

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

+ [x] OWASP Scan passes on CircleCI

**Comment by alexsoble** [comment]
Great! @lfrohlich, QASP review has passed, I recommend that you merge in this PR.

**Pull request merged**
