### PR TITLE
Disable Docker Layer Caching

### PR DESCRIPTION
**Pull request by alexsoble**
# Story / AC 

+ https://github.com/raft-tech/TANF-app/issues/285.

# Notes 

+ This PR copies over changes from https://github.com/raft-tech/TANF-app/pull/360/files to see if they get our frontend tests to go green on the HHS repository.

### CODE REVIEW

**Comment by alexsoble** [comment]
### Deliverable 1: Accepted Features

> *Performance Standard(s): At the beginning of each sprint, the Product Owner and development team will collaborate to define a set of user stories to be completed during the sprint. Acceptance criteria for each story will also be defined. The development team will deliver code and functionality to satisfy these user stories.*

> *Acceptable Quality Level: Delivered code meets the acceptance criteria for each user story. Incomplete stories will be assessed and considered for inclusion in the next sprint.*

How to check: 

+ [x] Look up the acceptance criteria in the related issue
+ [x] Check against the below criteria: 
+ [ ]  CircleCI tests execute on HHS repo branches without issue

### Deliverable 2: Tested Code

> *Performance Standard(s): Code delivered under the order must have substantial test code coverage. Version-controlled HHS GitHub repository of code that comprises products that will remain in the government domain.*

> *Acceptable Quality Level: Minimum of 90% test coverage of all code. All areas of code are meaningfully tested.*

How to check: 

+ Are code coverage minimums met? 
  + [x] Frontend coverage: 100% (see https://github.com/raft-tech/TANF-app README coverage dashboard)
  + [x] Backend coverage: 99% (see https://github.com/raft-tech/TANF-app README coverage dashboard)

### Deliverable 3: Properly Styled Code

> *Performance Standard(s): GSA 18F Front- End Guide*

> *Acceptable Quality Level: 0 linting errors and 0 warnings*

_This PR does not affect code styling; no Python or Javascript changes made._

### Deliverable 4: Accessible

> *Performance Standard(s): Web Content Accessibility Guidelines 2.1 AA standards*

> *Acceptable Quality Level: 0 errors reported using an automated scanner and 0 errors reported in manual testing*

_This PR does not affect accessibility; no front-end changes._

### Deliverable 5: Deployed

> *Performance Standard(s): Code must successfully build and deploy into the staging environment.*

> *Acceptable Quality Level: Successful build with a single command*

How to check: 

+ [x] Code successfully deployed via automated CircleCI process to development apps on Cloud.gov. 

### Deliverable 6: Documented

> *Performance Standard(s): Summary of user stories completed every two weeks. All dependencies are listed and the licenses are documented. Major functionality in the software/source code is documented, including system diagram. Individual methods are documented inline in a format that permits the use of tools such as JSDoc. All non-inherited 800-53 system security controls are documented in the Open Control or OSCAL format and HHS Section 508 Product Assessment Template (PAT) are updated as appropriate.*

> *Acceptable Quality Level: Combination of manual review and automated testing, if available*

How to check: 

_This PR does not substantially affect documentation._

### Deliverable 7: Secure

> *Performance Standard(s): Open Web Application Security Project (OWASP) Application Security Verification Standard 3.0*

> *Acceptable Quality Level: Code submitted must be free of medium- and high-level static and dynamic security vulnerabilities*

How to check: 

+ [x] Automated check: OWASP Scan passing on CircleCI.

**Comment by alexsoble** [comment]
@lfrohlich, I left more details in Slack, but I think this PR passes QASP review. The two CircleCI test steps now pass; we can handle the "Waiting for status to be reported" deploy step separately.

@iamjolly, am I right in assuming we need your sign off on small PRs like this one? The team is moving to a "multiple-PRs-per-sprint" model, I hope that doesn't create too much overhead or push too much reviewing & approving your way.

**Review by lfrohlich — APPROVED** [review]
This looks good to me.

**Comment by iamjolly** [comment]
@alexsoble - I likely only need to review PRs that have front-end changes, or ones where accessibility scans are changed in the CI process. This one seems like it is neither, so it's approved by me without running accessibility tests.

**Review by iamjolly — APPROVED** [review]

**Comment by alexsoble** [comment]
@iamjolly Sounds good, that works for me!

**Pull request merged**
